// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SMSServer.EFRepo;
using System;

namespace SMSServer.Migrations
{
    [DbContext(typeof(SMSDbContext))]
    [Migration("20180630091908_kkk")]
    partial class kkk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SMSServer.EFRepo.SMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<DateTime>("SendTime");

                    b.Property<string>("Sender");

                    b.Property<string>("UserCode");

                    b.HasKey("Id");

                    b.ToTable("SMS");
                });
#pragma warning restore 612, 618
        }
    }
}
